const USER_AUTHENTICATE = "USER_AUTHENTICATE";
const USER_REGISTER = "USER_REGISTER";
const USER_LOGOUT = "USER_LOGOUT";

const authConstant = {
	USER_AUTHENTICATE,
	USER_REGISTER,
	USER_LOGOUT,
};

export default authConstant;
